"""Shared fixtures: clean prove/verify inputs loaded from tests/data/.

The fixtures are generated by scripts/extract_* and committed; this only reads
them back into the dataclasses prove()/verify() take.
"""

import base64
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import pytest

import pylongfellow as lf

_DATA = Path(__file__).parent / "data"


@dataclass(frozen=True)
class VerifyInputs:
    circuit: bytes
    issuer_pk: tuple[int, int]
    transcript: bytes
    attrs: list[lf.RequestedAttribute]
    timestamp: datetime
    proof: bytes
    doctype: str
    spec: lf.ZkSpec


@dataclass(frozen=True)
class ProveInputs:
    circuit: bytes
    mdoc: bytes
    issuer_pk: tuple[int, int]
    transcript: bytes
    attrs: list[lf.RequestedAttribute]
    timestamp: datetime
    doctype: str
    spec: lf.ZkSpec


def _attrs(fixture) -> list[lf.RequestedAttribute]:
    return [
        lf.RequestedAttribute(attr["namespace"], attr["id"], bytes.fromhex(attr["cbor_value_hex"]))
        for attr in fixture["attrs"]
    ]


def _load_verify(name: str) -> VerifyInputs:
    fixture = json.loads((_DATA / f"{name}.json").read_text())
    spec = lf.find_zk_spec(fixture["system"], fixture["circuit_hash"])
    assert spec is not None, f"no spec for {fixture['circuit_hash']}"
    return VerifyInputs(
        circuit=(_DATA / "circuits" / fixture["circuit_hash"]).read_bytes(),
        issuer_pk=(int(fixture["issuer_pk_x"], 16), int(fixture["issuer_pk_y"], 16)),
        transcript=base64.b64decode(fixture["transcript_b64"]),
        attrs=_attrs(fixture),
        timestamp=datetime.fromisoformat(fixture["timestamp"]),
        proof=base64.b64decode(fixture["proof_b64"]),
        doctype=fixture["doctype"],
        spec=spec,
    )


def _load_prove(name: str) -> ProveInputs:
    fixture = json.loads((_DATA / f"{name}.json").read_text())
    spec = lf.find_zk_spec(fixture["system"], fixture["circuit_hash"])
    assert spec is not None, f"no spec for {fixture['circuit_hash']}"
    return ProveInputs(
        circuit=(_DATA / "circuits" / fixture["circuit_hash"]).read_bytes(),
        mdoc=bytes.fromhex(fixture["mdoc_hex"]),
        issuer_pk=(int(fixture["issuer_pk_x"], 16), int(fixture["issuer_pk_y"], 16)),
        transcript=bytes.fromhex(fixture["transcript_hex"]),
        attrs=_attrs(fixture),
        timestamp=datetime.fromisoformat(fixture["timestamp"]),
        doctype=fixture["doctype"],
        spec=spec,
    )


@pytest.fixture
def proof_age_over_18() -> VerifyInputs:
    return _load_verify("proof_age_over_18")


@pytest.fixture
def mdoc_eu_av() -> ProveInputs:
    return _load_prove("mdoc_eu_av")
