"""Generation drift check over the latest circuit per attribute count.

Each circuit is regenerated at test time on the google-cpp backend and scored
against its committed sidecar. A changed circuit_id fails the case (generation
drift); a changed byte hash at a stable circuit_id is emitted as an
ObservationWarning (serialization drift) without failing. circuit_id also
recomputes the committed id from the generated bytes.
"""

import hashlib
import io
import warnings

import pytest
import zstandard

from pylongfellow.backends import google_cpp

from .conftest import CIRCUIT_ID_FUNCTIONS, CIRCUITS, Circuit, ObservationWarning, spec_of


def _latest_per_attr_count() -> list[Circuit]:
    # google's generate_circuit only makes the latest version for a given
    # num_attributes; an older spec is rejected, so an older sidecar is not a
    # generation case.
    latest: dict[int, Circuit] = {}
    for circuit in CIRCUITS:
        current = latest.get(circuit.num_attributes)
        if current is None or circuit.version > current.version:
            latest[circuit.num_attributes] = circuit
    return [latest[count] for count in sorted(latest)]


GENERATION_PARAMS = [pytest.param(circuit, id=circuit.stem) for circuit in _latest_per_attr_count()]

# Generation exists only on google-cpp and dominates the cost of every case in
# this module, so each circuit is generated once and shared across cases.
_GENERATED: dict[str, bytes] = {}


def _generated(longfellow_for, circuit: Circuit) -> bytes:
    if circuit.stem not in _GENERATED:
        longfellow = longfellow_for("google-cpp", circuit)
        _GENERATED[circuit.stem] = longfellow.generate_circuit(spec_of(circuit))
    return _GENERATED[circuit.stem]


@pytest.mark.slow
@pytest.mark.parametrize("circuit", GENERATION_PARAMS)
def test_generation(circuit: Circuit, longfellow_for):
    generated = _generated(longfellow_for, circuit)
    assert google_cpp.circuit_id(generated) == circuit.circuit_id

    # The comparison is over decompressed bytes: the zstd envelope differs
    # between upstream's export pipeline and the runtime generate path (and
    # varies with zstd versions) while wrapping an identical serialization.
    def _decompressed_sha256(blob: bytes) -> str:
        reader = zstandard.ZstdDecompressor().stream_reader(io.BytesIO(blob))
        return hashlib.sha256(reader.read()).hexdigest()

    generated_sha256 = _decompressed_sha256(generated)
    committed_sha256 = _decompressed_sha256(circuit.path.read_bytes())
    if generated_sha256 != committed_sha256:
        warnings.warn(
            ObservationWarning(
                f"observation: serialization drift: {circuit.stem} "
                f"generated {generated_sha256[:12]} != committed {committed_sha256[:12]} "
                f"(decompressed)"
            ),
            stacklevel=2,
        )


GENERATED_ID_PARAMS = [
    pytest.param(circuit, id=f"{circuit.stem}-generated-circuit-id")
    for circuit in _latest_per_attr_count()
]


@pytest.mark.slow
@pytest.mark.parametrize("circuit", GENERATED_ID_PARAMS)
def test_generated_circuit_id(circuit: Circuit, longfellow_for):
    """The committed id is recomputed from freshly generated bytes."""
    generated = _generated(longfellow_for, circuit)
    assert CIRCUIT_ID_FUNCTIONS(generated) == circuit.circuit_id
